name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Badges
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Badges
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.PAT }}
          CREDLY_USER: cole-david.2db5ddb5
          
